# Site settings
title: Bloomberg Businessweek Design 2015
email: alex.kiko@gmail.com
description: ""
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
